#!/usr/bin/env python3
"""Check kernel stack usage against configured limits.

Reads .su files generated by -fstack-usage and reports any function
whose stack usage exceeds CONFIG_STACK_SIZE (64 KiB default).
"""
import os
import sys
import glob
import re

BUILD_DIR = 'build'
MAX_STACK = 65536  # CONFIG_STACK_SIZE

def main():
    su_files = glob.glob(os.path.join(BUILD_DIR, '**', '*.su'), recursive=True)
    if not su_files:
        print("[STACK] No .su files found (build with -fstack-usage)")
        return 0

    worst = 0
    worst_func = ""
    violations = 0

    for su_path in su_files:
        with open(su_path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Format: file:line:col:function\tbytes\ttype
                if '\t' not in line:
                    continue
                parts = line.split('\t')
                if len(parts) < 3:
                    continue
                try:
                    size = int(parts[-2])
                except ValueError:
                    continue
                func_part = parts[0]
                func = func_part.split(':')[-1] if ':' in func_part else func_part
                if size > worst:
                    worst = size
                    worst_func = func
                if size > MAX_STACK:
                    print(f"[STACK] VIOLATION: {func} uses {size} bytes "
                          f"(max {MAX_STACK}) in {su_path}")
                    violations += 1

    print(f"[STACK] Checked {len(su_files)} .su files, "
          f"worst: {worst_func}={worst} bytes, "
          f"violations={violations}")
    return 1 if violations else 0

if __name__ == '__main__':
    sys.exit(main())
